### ISSUE TITLE
Enhancement: Support for Accelerator in Cloud Properties

### ISSUE THREAD

**Issue by victorfong** [cloudfoundry/bosh-google-cpi-release#155]
I have come across an use case that require GPU on some of the Bosh deployed VM in GCP. I'm proposing that the manifest would look something like this:

```
resource_pools:
- name: common
  network: private
  stemcell:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    zone: us-east1-d
    region: us-east1
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    accelerator:
      type: nvidia-tesla-k80
      count: 1
```

Behavior will not change if user does not fill out the `accelerator` properties. During VM creation, we'll pass in something like `--accelerator type=nvidia-tesla-k80,count=1`. 

If it's ok with the community, my team can submit a PR for this enhancement. In the mean time, please let me know if there is any question or concern. 

Thanks,
Victor
