### ISSUE TITLE
Loss of network when using `migrated_from`

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry/bosh-google-cpi-release#317]
Howdie!

Yesterday we renamed all of our workers using [`migrated_from`]( https://bosh.io/docs/migrated-from/) . 

```
- name: teamx
   ....
  migrated_from:
  - name: concourse-worker-teamx
```

Upon deploying bosh correctly changed the name of the Jobs, and everything was working as expected except that all our workers lost connectivity to the internet. Internal GCP networking between ATCs and workers was still working.

The only solution to get back to a working state was to `bosh -d concourse recreate`.

Anyone has any idea what could have happened?
