### ISSUE TITLE
`ephemeral_disk_type: local-ssd` is not compatible with persistent disks

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh-google-cpi-release#346]
As reported by Tim Leong:

The BOSH Agent incorrectly looks for `/dev/sdc` for the persistent disk instead of looking for `/dev/sdb` (which would normally be the ephemeral disk, but the ephemeral disk is using `/dev/nvme`, so the persistent disk is now `/dev/sdb`).

Stemcell 1.360

When deploying to GCP, we witness the following failure:

```
          Task 956 | 18:57:47 | L executing post-stop: worker/3ab61249-2d9b-41b7-83c0-6630c017824e (0) (canary) (00:04:07)  
                              L Error: Action Failed get_task: Task b3bdddd4-f917-4740-795b-cf9c9ee62152 result: Adjusting persistent disk partitioning: Getting real device path: Resolving mapped device path: Timed out getting real device path for /dev/sdc  
          Task 956 | 19:01:52 | Error: Action Failed get_task: Task b3bdddd4-f917-4740-795b-cf9c9ee62152 result: Adjusting persistent disk partitioning: Getting real device path: Resolving mapped device path: Timed out getting real device path for /dev/sdc  
```

The VM_types:

```yaml
vm_types:
            - cloud_properties:
                accelerators:
                - count: 1
                  type: nvidia-tesla-t4
                ephemeral_disk_type: local-ssd
                machine_type: n1-standard-8
                on_host_maintenance: TERMINATE
                root_disk_size_gb: 25
                root_disk_type: pd-ssd
              name: gpu-t4
            - cloud_properties:
                accelerators:
                - count: 1
                  type: nvidia-tesla-v100
                ephemeral_disk_type: local-ssd
                machine_type: n1-standard-8
                on_host_maintenance: TERMINATE
                root_disk_size_gb: 25
                root_disk_type: pd-ssd
              name: gpu-v100
            - cloud_properties:
                machine_type: g2-standard-8
                on_host_maintenance: TERMINATE
                root_disk_size_gb: 50
                root_disk_type: pd-ssd
              name: gpu-l4
```
